---

- hosts: all

  tasks:
    - name: Install PIP
      shell: "apt-get -y install --reinstall python3-pip"
      become: true
    
    
    - name: Install latest JupyterLab Environment
      shell: "pip install --upgrade jupyterlab"
      become: true

    - name: start JupyterLab server
      shell: jupyter lab 